name: porqueno
favicon: null
layout_spectrum: 0.49100339226424694
typography_spectrum: 0.16156600462272763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.32385659753344953
  lightness: 0.8024915282148868
  saturation: 0.9943522005341947
  rhythmicContrast: 0.78009541798383
purpose: []
