name: porqueno
favicon: null
layout_spectrum: 0.24898
typography_spectrum: 0.24262
title: ¿Por Que No?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0eaec'
    - '#f2b7c9'
    - '#b26174'
    - '#ba1d2f'
    - '#496361'
  brandStrength: 0.75
  lightness: 0.8024915282148868
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
